server.port: 8090

spring:
  application:
    name: spa
  datasource:
    url: jdbc:h2:mem:mydb
    username: myuser
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false